//crear tabla de usuarios
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  password VARCHAR(100) NOT NULL,
  profileimage VARCHAR(200)
);
ALTER TABLE users
ADD COLUMN createdAt TIMESTAMP DEFAULT NOW() NOT NULL;

ALTER TABLE users
ADD COLUMN updatedAt TIMESTAMP DEFAULT NOW() NOT NULL;
